server:
  port: 7774

spring:
  application:
    name: unify-errand
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${ERRAND_DB_HOST:bobchasm.cn}:3306/unify_errand
    username: ${ERRAND_DB_USER:elm_app}
    password: ${ERRAND_DB_PASSWORD:ElmApp@2026!}
    hikari:
      transaction-isolation: TRANSACTION_READ_COMMITTED
  cloud:
    nacos:
      discovery:
        server-addr: bobchasm.cn
        namespace: public
        group: DEFAULT_GROUP
        username: nacos
        password: nacos
        ip: 127.0.0.1
        port: ${server.port}
        enabled: true
        register-enabled: true
        metadata:
          version: 1.0
        heartbeat:
          interval: 5000

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui
  packages-to-scan:
    - com.tju.unify.conv.errand.controller
  paths-to-match:
    - /unify-api/**

logging:
  level:
    com.tju.unify.conv.errand: debug
  pattern:
    dateformat: HH:mm:ss:SSS
  file:
    path: "logs/${spring.application.name}"
