server:
  port: 7070

spring:
  application:
    name: unify-gateway
  cloud:
    nacos:
      server-addr: bobchasm.cn:8848
      username: nacos
      password: nacos
    gateway:
      routes:
        # 电商服务集群
        - id: gateway
          uri: lb://gateway
          predicates:
            - Path=/api/**,/ws/**

unify:
  auth:
    excludePaths:
      - /api/**
      - /ws/**

# JWT配置
jwt:
  secret: abcdefghijklmnopqrstuvwxyz1234567890abcdefghijklmnopqrstuvwxyz1234567890abcdefghijklmnopqrstuvwxyz123456
  token-validity-in-seconds: 86400
  token-validity-in-seconds-for-remember-me: 108000

# 日志配置
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.tju.elm.gateway: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.netty: DEBUG